image:
  file: .gitpod.Dockerfile

# init tasks are ran in prebuilds, command tasks are run when the user starts a new session.
tasks:
  - name: Install Packages (Global)
    init: |
      yarn

  - name: Setup Web/Api Server
    # TODO: Use Docker Compose instead for starting development servers
    command: |
      yarn setup
      yarn dev

vscode:
  extensions:
    # Prettier VS Code extension
    - esbenp.prettier-vscode
    # VS Code intgration for ShellCheck so see the docs on how to ignore errors, among other things
    - timonwong.shellcheck
    # VS Code icon theme Fireship.io uses (Disclaimer: @ajhalili2006 is an fan of Fireship)
    - vscode-icons-team.vscode-icons
    # GitLens for seeing file annonations and more
    - eamodio.gitlens
    # Wait a sec, Docker stuff?
    - ms-azuretools.vscode-docker

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
